services:
  service-backend:
    container_name: tutor-scheduling
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8088:8080"
    networks:
      backend:
        aliases:
          - "service-backend"
networks:
  backend:
    driver: bridge