spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/workshop
    username: root
    password: rootpass
    jpa:
      hibernate.ddl-auto: validate
      generate-ddl: true
      show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
